### ISSUE TITLE
GXT produced blank output

### ISSUE THREAD

**Issue by clienthax** [xdanieldzd/Scarlet#2]
produces a 1024*1024 blank white png
https://mega.nz/#!OIVVHKBB!YXRxry3fhw9Jg8PwNPagrwW1zvWQiNwdtfDUBMAx7K8

**Comment by xdanieldzd** [comment]
This GXT ostensibly uses ARGB4444, so four channels of 4 bits each, but every pixel has an alpha value of zero, so nothing is shown. If I force the alpha channel to be fully opaque, the resulting image is characters of different colors overlapping one another:

![Screenshot](http://i.imgur.com/5ALc1ld.png)

My guess would be that the game specifically interprets this file's pixel data differently from normal GXTs, and only uses the GXT structure as a convenient container -- maybe the pixel data is meant to be four 1024x1024 sheets of characters, with each channel holding the intensity of a full pixel on each sheet...?

I really am not sure if I can do anything about this, so you might have to write your own converter for this.
