### ISSUE TITLE
Decrypt SHTX and SHTXFS before convert them to PNG. 

### ISSUE THREAD

**Issue by Liquid-S** [xdanieldzd/Scarlet#3]
There are lots of images in Danganronpa 1, 2 and Another Episode for PSVITA that are encrypted, so I was wondering whether you could add to your tool the code done by BlackDragon --> https://github.com/BlackDragonHunt/Danganronpa-Tools/blob/master/dr_dec.py
That way it won't be necessary anymore to use dr_dec.py before using your tool and users won't need to install python either.

**Comment by xdanieldzd** [comment]
Added in commit ad79158cc0e0fc9934c29d4b9d41b8b03850165b, based on BlackDragonHunt's script. I've only tested this with about 100 files from Danganronpa Another Episode that I have here, but these all appear to decompress, and of course convert to PNG correctly.

I'm still considering this not well tested yet, tho, so if you're able to build Scarlet yourself, it would be great if you could maybe test more files from the other games, and give some feedback as to whether they convert properly or not.

**Comment by Liquid-S** [comment]
Thank you very much for adding the decompression!
I'm gonna test the tool, don't worry!

There are some black lines in some images. These ones are from DR2 (PSVITA).
I can send you the files, if you need them.
![screenshot 2016-11-30 19 35 33](https://cloud.githubusercontent.com/assets/22280453/20765900/8b109604-b734-11e6-9c4b-fd2ae4f1967f.png)

**Comment by xdanieldzd** [comment]
It would be great if you could ex. pack up and upload any files that have issues, such as these black lines.

As for the tool not deleting the decompressed images, the way it currently works might not lend itself to automatically deleting them, but I'll have a look into making that an option.

**Comment by Liquid-S** [comment]
Inside this zip you can find some of those files with black and grey lines.
[fla_411.zip](https://github.com/xdanieldzd/Scarlet/files/631781/fla_411.zip)

Understood, thank you!

**Comment by xdanieldzd** [comment]
Possibly fixed the black lines with commit 8bd483dc704fda1372726da7f5a7f765a59c7ce7. This still needs more testing with GXTs from other games, tho, as there's a chance that I might've broken conversion of some of them. I'll be doing that later today or tomorrow but so far it's looking alright, with previously problematic images from ex. Dengeki Bunko Fighting Climax and Puyo Puyo Tetris still converting fine.

Do feel free to try out this latest commit and check if you're still getting lines in any of the Danganronpa GXTs!

![temp473](https://cloud.githubusercontent.com/assets/7199225/20909621/20644e7c-bb5d-11e6-99ab-ca1a897efa11.png)

**Comment by Liquid-S** [comment]
Everything seems to be ok with the DR GXTs.
Thank you very much!

**Comment by xdanieldzd** [comment]
Hm, I had to revert 8bd483d because it turned out to be causing problems with GXTs from various other games. So, for the Danganronpa GXTs, you should stay on that commit until I've worked out the correct fix for this issue; I'll also keep this report open.
